//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class cash_flow_info
    {
        public int id { get; set; }
        public int user_id { get; set; }
        public short month { get; set; }
        public decimal money_start { get; set; }
        public decimal money_end { get; set; }
    }
}
