//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class cash_flow_history
    {
        public int id { get; set; }
        public int category_id { get; set; }
        public int user_id { get; set; }
        public System.DateTime date { get; set; }
        public double money { get; set; }
        public short month { get; set; }
        public string comment { get; set; }
        public Nullable<short> amortization_months { get; set; }
    }
}
