//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class cash_flow_category
    {
        public int id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public int activity_id { get; set; }
        public string title { get; set; }
        public bool is_income { get; set; }
        public bool is_main { get; set; }
        public Nullable<bool> is_direct_expense { get; set; }
    }
}
