//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class cash_flow_statement
    {
        public int id { get; set; }
        public int category_id { get; set; }
        public decimal money { get; set; }
        public short month { get; set; }
    
        public virtual cash_flow_category cash_flow_category { get; set; }
    }
}
