//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelGenerator
{
    using System;
    using System.Collections.Generic;
    
    public partial class category_history
    {
        public int id { get; set; }
        public int category_id { get; set; }
        public System.DateTime date { get; set; }
        public int ordinatory_payment { get; set; }
    
        public virtual category category { get; set; }
    }
}
