//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelGenerator
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kepartners_data2Entities : DbContext
    {
        private static kepartners_data2Entities _context;

        public kepartners_data2Entities()
            : base("name=kepartners_data2Entities")
        {
        }
        public static kepartners_data2Entities GetContext()
        {
            if (_context == null)
                _context = new kepartners_data2Entities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<activity> activity { get; set; }
        public virtual DbSet<cash_flow_activity> cash_flow_activity { get; set; }
        public virtual DbSet<cash_flow_category> cash_flow_category { get; set; }
        public virtual DbSet<cash_flow_history> cash_flow_history { get; set; }
        public virtual DbSet<cash_flow_info> cash_flow_info { get; set; }
        public virtual DbSet<cash_flow_statement> cash_flow_statement { get; set; }
        public virtual DbSet<category> category { get; set; }
        public virtual DbSet<category_history> category_history { get; set; }
        public virtual DbSet<registry> registry { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
